import torch
import torch.nn as nn
import torch.nn.functional as F

class KANLinear(nn.Module):
    """
    A KAN layer utilizing B-splines (Piecewise Polynomials).
    This implementation uses the Cox-de Boor recursive algorithm to calculate 
    local basis functions over a grid of knots.
    """
    def __init__(self, in_features: int, out_features: int, grid_size: int = 5, spline_order: int = 3):
        super(KANLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.grid_size = grid_size
        self.spline_order = spline_order
        
        # The number of basis functions generated by the B-spline
        self.num_bases = grid_size + spline_order
        
        # Learnable coefficients for the B-splines
        self.spline_weight = nn.Parameter(torch.empty(out_features, in_features, self.num_bases))
        nn.init.xavier_normal_(self.spline_weight)
        
        # Base activation path (SiLU) for training stability
        self.base_activation = nn.SiLU()
        self.base_weight = nn.Parameter(torch.empty(out_features, in_features))
        nn.init.xavier_normal_(self.base_weight)
        
        # Initialize the static knot grid
        # We define a grid over the range [-1, 1], padded by the spline_order on both sides
        step = 2.0 / grid_size
        grid_array = torch.arange(-spline_order, grid_size + spline_order + 1, dtype=torch.float32) * step - 1.0
        
        # Register the grid as a buffer so it moves to the GPU automatically but doesn't get updated by the optimizer
        self.register_buffer('grid', grid_array.unsqueeze(0).expand(in_features, -1))

    def b_splines(self, x: torch.Tensor) -> torch.Tensor:
        """
        Calculates the B-spline basis functions using the Cox-de Boor algorithm.
        """
        # Add an extra dimension for broadcasting against the knot grid
        # Shape: (batch_size, in_features, 1)
        x = x.unsqueeze(-1)
        
        # Base case: 0-degree B-splines (Indicator functions)
        # Returns 1 if x is between two adjacent knots, else 0
        bases = ((x >= self.grid[:, :-1]) & (x < self.grid[:, 1:])).float()
        
        # Recursive step: calculate higher degree B-splines
        for k in range(1, self.spline_order + 1):
            # Calculate denominators, adding a tiny epsilon to prevent division by zero
            left_denom = self.grid[:, k:-1] - self.grid[:, :-(k+1)] + 1e-8
            right_denom = self.grid[:, k+1:] - self.grid[:, 1:-k] + 1e-8
            
            # Calculate left and right interpolation terms
            left_term = (x - self.grid[:, :-(k+1)]) / left_denom
            right_term = (self.grid[:, k+1:] - x) / right_denom
            
            # Combine to get the next degree of basis functions
            bases = left_term * bases[:, :, :-1] + right_term * bases[:, :, 1:]
            
        return bases # Final shape: (batch_size, in_features, grid_size + spline_order)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Tensor of shape (batch_size, in_features)
        Returns:
            Tensor of shape (batch_size, out_features)
        """
        # Clamp inputs to strictly fall within our defined grid [-1, 1]
        # This prevents out-of-bounds errors on massive LOB data spikes
        x_clamped = torch.tanh(x)
        
        # Generate B-spline bases
        spline_bases = self.b_splines(x_clamped) 
        
        # Sum of products across input features and B-spline bases
        # b = batch, i = in_features, s = spline bases, o = out_features
        spline_out = torch.einsum('bis,ois->bo', spline_bases, self.spline_weight)
        
        # Base linear path
        base_out = F.linear(self.base_activation(x), self.base_weight)
        
        return spline_out + base_out


class TKANCell(nn.Module):
    """
    A recurrent cell utilizing a B-spline KAN layer to process the combined hidden state and input.
    """
    def __init__(self, input_size: int, hidden_size: int, grid_size: int = 5, spline_order: int = 3):
        super(TKANCell, self).__init__()
        self.hidden_size = hidden_size
        self.kan_layer = KANLinear(input_size + hidden_size, hidden_size, grid_size, spline_order)

    def forward(self, x_t: torch.Tensor, h_prev: torch.Tensor) -> torch.Tensor:
        combined = torch.cat([x_t, h_prev], dim=1)
        h_t = torch.tanh(self.kan_layer(combined))
        return h_t


class TKANClassifier(nn.Module):
    """
    Complete Temporal KAN architecture for multivariate time-series classification using B-splines.
    """
    def __init__(self, input_size: int = 15, hidden_size: int = 8, 
                 num_classes: int = 3, num_layers: int = 1, grid_size: int = 5, spline_order: int = 3):
        super(TKANClassifier, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.cells = nn.ModuleList([
            TKANCell(
                input_size=input_size if i == 0 else hidden_size, 
                hidden_size=hidden_size, 
                grid_size=grid_size,
                spline_order=spline_order
            ) for i in range(num_layers)
        ])
        
        self.layer_norm = nn.LayerNorm(hidden_size)
        self.classifier_head = nn.Linear(hidden_size, num_classes)
        #self.classifier_head = KANLinear(hidden_size, num_classes, grid_size, spline_order)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        batch_size, seq_length, _ = x.size()
        
        h = [torch.zeros(batch_size, self.hidden_size, device=x.device) for _ in range(self.num_layers)]
        
        for t in range(seq_length):
            x_t = x[:, t, :]
            
            for layer_idx in range(self.num_layers):
                h[layer_idx] = self.cells[layer_idx](x_t, h[layer_idx])
                x_t = h[layer_idx] 
                
        final_h = self.layer_norm(h[-1])
        logits = self.classifier_head(final_h)
        #logits = self.classifier_head(final_h)
        return logits